server:
  port: 9000

spring:
  datasource:
    url: jdbc:mysql://localhost/social_network?useSSL=false
    username: ${NACS_MYSQL_USERNAME}
    password: ${NACS_MYSQL_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
